### PR TITLE
Add support for Asciidoctor RevealJS backend

### PR DESCRIPTION
**Pull request by gscheibel**

### CODE REVIEW

**Comment by pledbrook** [comment]
Before I merge this in, have you thought of hosting this template (and any others you create) yourself? I can then link the package from your Bintray account to the Lazybones one. This gives you greater control over the source repository for the template.

To be honest, I'm trying to move away from hosting template sources in this repository, but I'll accept the PR if you really don't want to manage it yourself. Let me know what your thoughts are on this.

**Comment by gscheibel** [comment]
Hello Peter,

I've set a bintray repo up (
https://bintray.com/gscheibel/asciidoctor-lazybones), configured my project
with:

lazybones {
    repositoryName = 'gscheibel/asciidoctor-lazybones'
    repositoryUsername = project.bintrayUsername
    repositoryApiKey = project.bintrayApiKey
}

in the build.gradle but when I run 'gradle publishAllTemplates' I get a:
Could not create package 'asciidoctor-revealjs-template': Bad Request

In the logs I can see:

Creating package asciidoctor-revealjs-template via
https://api.bintray.com/packages/gscheibel/asciidoctor-lazybones
Failed to create package asciidoctor-revealjs-template. Response from
Bintray:
{"message":"Package for path 'gscheibel/asciidoctor-lazybones' was invalid.
Package license is mandatory"}
:publishTemplateAsciidoctorRevealjs FAILED

I can't find where / how to configure the licence.

any thoughts ?

Cheers,
Guillaume

**Comment by gscheibel** [comment]
to fix the license issue I've added 'license' to the lazybones block but I have now a the same kind of error with the VCS URL:

Failed to create package asciidoctor-revealjs-template. Response from Bintray:
{"message":"Please enter a valid VCS URL for your OSS package."}

Therefore the VCSUrl property is not exposed by the LazybonesConventions conventions.

**Comment by pledbrook** [comment]
OK, thanks for the information. This may be a new requirement for Bintray, which will require a change to the Gradle plugin as you suggest. Let me look into it at the end of the week.

**Comment by pledbrook** [comment]
I found at that this is an extra requirement for new packages, although apparently not that recent. I haven't get round to implementing it yet, but plan to look into it soon. Bear with me.

**Comment by pledbrook** [comment]
If you upgrade to v1.2.4 of the plugin, you can add a `vcsUrl` property to the `lazybones` configuration block. It's just a string URL.

**Comment by gscheibel** [comment]
@pledbrook I have pushed the first template within the Asciidoctor org on Bintray (https://bintray.com/asciidoctor/maven/asciidoctor-revealjs-template/view) how can I make it available via "lazybones list / create" ? Do I have to push into the lazybone org ? (If so, can I have write rights ?)

Cheers,
Guillaume

**Comment by pledbrook** [comment]
You should be able to go to the [`lazybones-templates`|https://bintray.com/pledbrook/lazybones-templates] project on Bintray and request to have your package included from there.

**Pull request closed without merging**
